spring:
  application:
    name: product
  datasource:
          url: jdbc:mysql://localhost:3306/springcloud_sale
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: 123456
  rabbitmq:
    host: 192.168.99.102
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  test
